import {ChevronDown,Diamond,Film,Plus,SkipBack,Play,Pause,Repeat2,Trash2} from 'lucide-react';
import type {Project,Command} from '../../shared/model';
export function Timeline({project,time,playing,selected,loop,onLoop,onPlay,onTime,onSelect,onAddClip,execute}:{project:Project;time:number;playing:boolean;selected:string|null;loop:boolean;onLoop:()=>void;onPlay:()=>void;onTime:(time:number)=>void;onSelect:(id:string)=>void;onAddClip:()=>void;execute:(c:Command)=>void}){
  const frame=Math.floor(time*project.fps);const seconds=Math.floor(time);
  const labels=Array.from({length:Math.min(13,Math.ceil(project.duration)+1)},(_,i)=>i*project.duration/Math.min(12,Math.ceil(project.duration)));
  const nodes=project.nodes.filter(n=>project.clips.some(c=>c.nodeId===n.id)||project.tracks.some(t=>t.nodeId===n.id)||n.id===selected);
  return <section className="timeline" aria-label="Dòng thời gian"><div className="timeline-header"><div className="timeline-title"><Film size={15}/><strong>Timeline</strong><span className="muted">Sequence 01</span><ChevronDown size={13}/></div><div className="transport"><button className="icon-button" onClick={()=>onTime(0)} title="Về đầu"><SkipBack size={15}/></button><button className="play-button" onClick={onPlay} title="Phát / dừng (Space)">{playing?<Pause size={15} fill="currentColor"/>:<Play size={15} fill="currentColor"/>}</button><button className={`icon-button ${loop?'active':''}`} onClick={onLoop} title="Lặp lại"><Repeat2 size={16}/></button><span className="timecode">00:{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}:<b>{String(frame%project.fps).padStart(2,'0')}</b></span><span className="muted">/ {project.duration.toFixed(1)}s</span></div><button className="quiet-button" onClick={onAddClip} disabled={!selected}><Plus size={14}/> Chuyển động</button></div>
    <div className="timeline-body"><div className="track-labels"><div className="track-heading">ĐỐI TƯỢNG <span>{nodes.length}</span></div>{nodes.map(n=><button key={n.id} className={`track-label ${selected===n.id?'selected':''}`} onClick={()=>onSelect(n.id)}><span className="track-dot" style={{background:project.assets.find(a=>a.id===n.assetId)?.color}}/>{n.name.split(' · ')[0]}<Diamond size={10}/></button>)}{project.shots.length>0&&<div className="track-label"><Film size={12}/> Camera cuts</div>}</div>
      <div className="track-grid"><div className="ruler" onPointerDown={e=>{const rect=e.currentTarget.getBoundingClientRect();onTime(Math.min(project.duration,Math.max(0,(e.clientX-rect.left)/rect.width*project.duration)));}}>{labels.map(t=><span key={t} style={{left:`${t/project.duration*100}%`}}>{t.toFixed(t%1?1:0)}s</span>)}</div>
        <div className="tracks" onDoubleClick={e=>{const rect=e.currentTarget.getBoundingClientRect();onTime(Math.max(0,Math.min(project.duration,(e.clientX-rect.left)/rect.width*project.duration)));}}>{nodes.map(n=><div key={n.id} className={`track-row ${selected===n.id?'selected':''}`} onClick={()=>onSelect(n.id)}>{project.clips.filter(c=>c.nodeId===n.id).map((c,i)=><div key={c.id} className={`clip ${c.preset==='wave'?'gold':'mint'}`} style={{left:`${c.start/project.duration*100}%`,width:`${c.duration/project.duration*100}%`,top:i%2===0?4:22,height:i%2===0?30:20,zIndex:i+1}} title={`${c.name} · ${c.start}s–${c.start+c.duration}s`}><span className="clip-wave">∿ ∿ ∿ ∿ ∿ ∿</span><span>{c.name}</span><button className="clip-delete" title={`Xóa ${c.name}`} onClick={e=>{e.stopPropagation();execute({op:'delete_clip',id:c.id});}}><Trash2 size={11}/></button></div>)}{project.tracks.filter(t=>t.nodeId===n.id).flatMap(t=>t.keys.map(k=><button key={`${t.id}-${k.time}`} className="keyframe-dot" title={`${t.property}: ${k.value} @ ${k.time}s`} style={{left:`${k.time/project.duration*100}%`}} onClick={()=>onTime(k.time)}><Diamond size={10} fill="currentColor"/></button>))}</div>)}{project.shots.length>0&&<div className="track-row">{project.shots.map(s=><div key={s.id} className="clip blue" style={{left:`${s.start/project.duration*100}%`,width:`${s.duration/project.duration*100}%`}}>{s.name}</div>)}</div>}</div>
        <div className="playhead" style={{left:`${time/project.duration*100}%`}}><span/></div>
      </div>
    </div><div className="timeline-footer"><span><span className="status-dot"/> {project.fps} FPS · {Math.round(project.duration*project.fps)} frames</span><span>Space <kbd>Phát</kbd> · Cuộn chuột <kbd>Zoom cảnh</kbd> · Ctrl Z <kbd>Hoàn tác</kbd></span><span>{project.tracks.reduce((n,t)=>n+t.keys.length,0)} keyframes</span></div>
  </section>;
}
