import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,Bone,Box,Camera,Check,ChevronDown,ChevronRight,Clapperboard,Code2,Copy,Eye,EyeOff,Film,FolderOpen,Grid2X2,Import,Layers,Lightbulb,LoaderCircle,Maximize2,MousePointer2,Move,Orbit,PanelLeftClose,Plus,Redo2,RotateCcw,Save,Search,Settings2,Shapes,Sparkles,Sun,Trash2,Undo2,X} from 'lucide-react';
import type {Asset,Command,Project,SceneNode} from '../shared/model';
import {createAsset,uid} from '../shared/templates';
import {api} from './api';
import {useStudio} from './useStudio';
import {Stage} from './engine/Stage';
import {AssetPreview} from './components/AssetPreview';
import {Timeline} from './components/Timeline';
import {Inspector} from './components/Inspector';
import {ModalPanel} from './components/ModalPanel';
import {useExporter} from './useExporter';
import {registerWebTools} from './webmcp';

export type Panel='create'|'animate'|'connect'|'export'|'story'|'project'|null;
export function App(){
  const studio=useStudio();const {project,execute}=studio;
  const [selected,setSelected]=useState<string|null>('milo'),[leftTab,setLeftTab]=useState<'assets'|'scene'>('assets'),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[panel,setPanel]=useState<Panel>(null),[inspectorTab,setInspectorTab]=useState<'object'|'scene'>('object');
  const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[loop,setLoop]=useState(true),[rig,setRig]=useState(false),[grid,setGrid]=useState(false),[orbit,setOrbit]=useState(false),[tool,setTool]=useState<'select'|'translate'|'rotate'|'scale'>('select'),[toast,setToast]=useState(''),[stageVersion,setStageVersion]=useState(0);
  const stage=useRef<Stage|null>(null),host=useRef<HTMLDivElement|null>(null),clock=useRef(0),player=useRef({playing,loop,duration:12}),mutateRef=useRef(execute),projectRef=useRef<Project|null>(project),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  mutateRef.current=execute;projectRef.current=project;player.current={playing,loop,duration:project?.duration??12};
  const notify=useCallback((message:string)=>{setToast(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),5000);},[]);
  const run=useCallback((c:Command)=>{void execute(c).catch(e=>notify(e.message));},[execute,notify]);
  const seek=useCallback((t:number)=>{clock.current=t;setTime(t);},[]);
  const exporting=useExporter({stage,projectRef,notify,setPlaying,clock,onDone:()=>{setTool('select');setGrid(false);}});
  const locked=exporting.active;
  useEffect(()=>{if(!project||!host.current||stage.current)return;try{const engine=new Stage(host.current,{onPick:setSelected,onTransform:(id,patch)=>{void mutateRef.current({op:'update_node',id,patch}).catch(e=>notify(e.message));},onError:notify});stage.current=engine;setStageVersion(v=>v+1);}catch(e){notify(`Không thể khởi tạo GPU: ${e instanceof Error?e.message:String(e)}`);}return()=>{stage.current?.dispose();stage.current=null;};},[Boolean(project),notify]);
  useEffect(()=>{if(project&&!locked){stage.current?.setProject(project);if(!project.nodes.some(n=>n.id===selected))setSelected(null);if(clock.current>project.duration)seek(project.duration);}},[project,selected,stageVersion,locked,seek]);
  useEffect(()=>{stage.current?.select(selected);stage.current?.setTool(tool);},[selected,tool,stageVersion]);
  useEffect(()=>stage.current?.setRig(rig),[rig,stageVersion]);useEffect(()=>stage.current?.setGrid(grid),[grid,stageVersion]);useEffect(()=>stage.current?.setOrbit(orbit),[orbit,stageVersion]);
  useEffect(()=>{let frame=0,last=performance.now(),uiLast=0;const tick=(now:number)=>{const dt=Math.min((now-last)/1000,0.1);last=now;if(!locked){if(player.current.playing){clock.current+=dt;if(clock.current>=player.current.duration){if(player.current.loop)clock.current%=player.current.duration;else{clock.current=player.current.duration;setPlaying(false);}}}stage.current?.draw(clock.current);if(now-uiLast>80&&player.current.playing){setTime(clock.current);uiLast=now;}}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[locked]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable="true"]')||panel||locked)return;if(e.code==='Space'){e.preventDefault();setPlaying(v=>!v);}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();run({op:e.shiftKey?'redo':'undo'});}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();notify('Mọi thay đổi đã được lưu tự động vào workspace.');}else if(e.key==='Delete'&&selected)run({op:'delete_node',id:selected});else if(e.key.toLowerCase()==='w')setTool('translate');else if(e.key.toLowerCase()==='e')setTool('rotate');else if(e.key.toLowerCase()==='r')setTool('scale');else if(e.key==='Escape'){setSelected(null);setTool('select');}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[panel,locked,run,selected,notify]);
  useEffect(()=>registerWebTools(()=>projectRef.current,execute),[execute]);
  const addToScene=async(asset:Asset)=>{const node:SceneNode={id:uid('node'),assetId:asset.id,name:asset.name,position:[0,0,1],rotation:[0,0,0],scale:[1,1,1],visible:true,castShadow:true};try{await execute({op:'add_node',node});setSelected(node.id);notify(`Đã thêm ${asset.name}`);}catch(e){notify((e as Error).message);}};
  const importInput=useRef<HTMLInputElement>(null);
  const importAsset=async(file:File)=>{try{notify(`Đang nhập ${file.name}…`);const {source}=await api.importFile(file);const model=source.endsWith('.glb');let width=2,height=3;if(!model){const bitmap=await createImageBitmap(file);width=height*bitmap.width/bitmap.height;bitmap.close();if(width>100)throw new Error('Ảnh có tỷ lệ quá rộng.');}const a:Asset={id:uid('asset'),name:file.name.replace(/\.[^.]+$/,''),kind:model?'model':'sprite',template:'custom',color:'#94b5bf',bones:[],parts:[],source,width,height,rigged:false};await execute({op:'add_asset',asset:a});await addToScene(a);}catch(e){notify((e as Error).message);}};
  const node=project?.nodes.find(n=>n.id===selected);const asset=project?.assets.find(a=>a.id===node?.assetId);
  const assets=project?.assets.filter(a=>(filter==='all'||a.kind===filter||(filter==='2d'&&a.kind!=='model'))&&a.name.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')))??[];
  if(!project)return <div className="connection-screen"><img src="/mark.svg" alt=""/><h1>Parallax Studio</h1><p>Xưởng hoạt hình 2D / 2.5D</p><div className="connection-card">{studio.error?<><Code2 size={24}/><h2>Kết nối lõi dựng phim</h2><p>Khởi động ứng dụng bằng <code>npm start</code>, sau đó kết nối lại.</p><small>{studio.error}</small><button className="primary-button" onClick={()=>void studio.connect()}>Kết nối lại</button></>:<><LoaderCircle className="spin"/><span>Đang mở workspace…</span></>}</div></div>;
  return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Parallax Studio"><img src="/mark.svg" alt=""/><span>parallax<span className="brand-studio">STUDIO</span></span></a><div className="project-crumb"><span className="crumb-divider"/><FolderOpen size={15}/><button onClick={()=>setPanel('project')}>{project.name}<ChevronDown size={13}/></button><span className="project-badge">2.5D</span><span className="saved"><span className={`status-dot ${studio.connected?'':'offline'}`}/>{studio.busy?'Đang lưu':studio.connected?'Đã lưu':'Mất kết nối'}</span></div><div className="top-actions"><button className="quiet-button connect-button" onClick={()=>setPanel('connect')}><Code2 size={15}/><span>Kết nối AI</span></button><button className="primary-button" onClick={()=>setPanel('export')} disabled={locked}><ArrowUpRight size={15}/>Xuất phim</button></div></header>
    <div className="workspace-tabs"><div className="workspace-tab active"><Clapperboard size={15}/>Dựng phim</div><button onClick={()=>{setRig(true);setInspectorTab('object');}}><Bone size={15}/>Rig & Animate</button><button onClick={()=>setPanel('story')}><Sparkles size={15}/>Kịch bản AI</button><div className="workspace-spacer"/><span className="workspace-note"><span className="status-dot"/> LOCAL WORKSPACE</span><button className="icon-button" onClick={()=>setPanel('project')} title="Cài đặt dự án"><Settings2 size={16}/></button></div>
    <main className={`workspace ${locked?'is-exporting':''}`}><aside className="library"><div className="panel-heading"><div className="mini-tabs"><button className={leftTab==='assets'?'active':''} onClick={()=>setLeftTab('assets')}>Thư viện</button><button className={leftTab==='scene'?'active':''} onClick={()=>setLeftTab('scene')}>Cấu trúc cảnh</button></div><Layers size={15}/></div>
      {leftTab==='assets'?<><div className="library-actions"><label className="search-field"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm asset…" aria-label="Tìm asset"/><span>⌕</span></label><div className="filter-row">{[['all','Tất cả'],['2d','2D'],['model','3D']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}<span>{assets.length} assets</span></div></div><div className="asset-grid">{assets.map(a=><button key={a.id} className={`asset-card ${a.id===asset?.id?'selected':''}`} onClick={()=>void addToScene(a)} draggable onDragStart={e=>e.dataTransfer.setData('parallax/asset',a.id)} title={`Thêm ${a.name} vào cảnh`}><div className={`asset-art ${a.kind}`}><AssetPreview asset={a}/><span className="asset-kind">{a.kind==='model'?'3D':'2D'}</span><span className="asset-add"><Plus size={14}/></span></div><span className="asset-name">{a.name.split(' · ')[0]}</span><span className="asset-meta">{a.kind==='character'?'Nhân vật':a.kind==='animal'?'Con vật':a.kind==='model'?'Model GLB':a.kind==='sprite'?'Ảnh nhập':'Đạo cụ'}{a.rigged&&a.bones.length>1&&<Bone size={11}/>}</span></button>)}{!assets.length&&<div className="empty-library">Không có asset phù hợp.</div>}</div><div className="library-bottom"><button className="create-asset-button" onClick={()=>setPanel('create')} disabled={locked}><Plus size={16}/>Tạo asset mới</button><button className="quiet-button import-button" onClick={()=>importInput.current?.click()} disabled={locked}><Import size={14}/>Nhập PNG / GLB</button><input ref={importInput} type="file" accept=".png,.jpg,.jpeg,.webp,.glb" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void importAsset(file);e.target.value='';}}/><div className="library-tip"><span>ASSET → SCENE</span>Kéo hoặc bấm asset để thêm vào cảnh.</div></div></>:<><div className="scene-root"><ChevronDown size={13}/><Film size={14}/>Sequence 01<span>{project.nodes.length}</span></div><div className="scene-tree">{project.nodes.map(n=><div key={n.id} className={`scene-item ${selected===n.id?'selected':''}`}><button onClick={()=>{setSelected(n.id);setInspectorTab('object');}}><Box size={14}/><span>{n.name}</span></button><button className="icon-button" title={n.visible?'Ẩn đối tượng':'Hiện đối tượng'} onClick={()=>run({op:'update_node',id:n.id,patch:{visible:!n.visible}})}>{n.visible?<Eye size={13}/>:<EyeOff size={13}/>}</button></div>)}<button className="scene-system" onClick={()=>setInspectorTab('scene')}><Camera size={15}/>Camera chính</button><button className="scene-system" onClick={()=>setInspectorTab('scene')}><Sun size={15}/>Ánh sáng mặt trời</button></div><div className="library-bottom"><button className="create-asset-button" onClick={()=>setPanel('create')}><Plus size={16}/>Thêm đối tượng</button></div></>}
    </aside><section className="center-panel"><div className="viewport-top"><div className="viewport-title"><span className="status-dot"/><strong>Scene 01</strong><ChevronRight size={12}/><span>Khu rừng lúc bình minh</span></div><div className="viewport-settings"><span>16:9</span><span className="mini-divider"/><button onClick={()=>setOrbit(v=>!v)} className={orbit?'active':''}><Camera size={13}/>{orbit?'Góc tự do':'Camera chính'}<ChevronDown size={12}/></button></div></div><div className="viewport" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const a=project.assets.find(a=>a.id===e.dataTransfer.getData('parallax/asset'));if(a&&!locked)void addToScene(a);}}><div className="stage-host" ref={host}/><div className="viewport-tools">{[{id:'select',icon:MousePointer2,title:'Chọn đối tượng'},{id:'translate',icon:Move,title:'Di chuyển (W)'},{id:'rotate',icon:RotateCcw,title:'Xoay (E)'},{id:'scale',icon:Maximize2,title:'Tỷ lệ (R)'}].map(({id,icon:Icon,title})=><button key={id} className={tool===id?'active':''} title={title} disabled={locked} onClick={()=>setTool(id as typeof tool)}><Icon size={17}/></button>)}<span/><button className={rig?'active':''} onClick={()=>setRig(v=>!v)} title="Hiện xương"><Bone size={18}/></button><button className={grid?'active':''} onClick={()=>setGrid(v=>!v)} title="Lưới mặt đất"><Grid2X2 size={17}/></button><button className={orbit?'active':''} onClick={()=>setOrbit(v=>!v)} title="Xoay góc nhìn bằng chuột"><Orbit size={18}/></button></div><div className="scene-caption"><span className="scene-label">{orbit?'PERSPECTIVE VIEW':'CAMERA VIEW'}</span><span>{project.nodes.filter(n=>n.visible).length} objects · {project.light.shadows?'Soft shadows':'Shadows off'}</span></div><div className="viewport-axis"><span className="axis-y">Y</span><span className="axis-z">Z</span><span className="axis-x">X</span><i/></div>{rig&&<div className="rig-label"><Bone size={13}/>Rig hiển thị · {asset?.bones.length??0} xương</div>}{locked&&<div className="render-overlay"><LoaderCircle className="spin" size={28}/><strong>Đang dựng phim</strong><span>{exporting.progress}</span><button onClick={exporting.cancel}>Hủy xuất phim</button></div>}</div><div className="viewport-bottom"><span><MousePointer2 size={12}/>{node?node.name:'Chọn một đối tượng để chỉnh sửa'}</span><div>{orbit&&<button onClick={()=>{const camera=stage.current?.getCamera();if(camera){run({op:'set_camera',patch:camera});setOrbit(false);notify('Đã lưu góc camera.');}}}><Camera size={13}/>Lưu góc nhìn</button>}<span>GPU · WebGL 2</span><span className="mini-divider"/><button onClick={()=>{setOrbit(false);setGrid(false);setRig(false);}}><Maximize2 size={13}/>Khung phim</button></div></div></section>
    <aside className="inspector"><div className="panel-heading"><div className="mini-tabs"><button className={inspectorTab==='object'?'active':''} onClick={()=>setInspectorTab('object')}>Thuộc tính</button><button className={inspectorTab==='scene'?'active':''} onClick={()=>setInspectorTab('scene')}>Cảnh & ánh sáng</button></div></div><Inspector project={project} node={node} asset={asset} tab={inspectorTab} time={time} rig={rig} onRig={()=>setRig(v=>!v)} run={run} onAnimate={()=>setPanel('animate')} onSelect={setSelected}/></aside></main>
    <Timeline project={project} time={time} playing={playing} selected={selected} loop={loop} onLoop={()=>setLoop(v=>!v)} onPlay={()=>{if(!locked){if(clock.current>=project.duration)seek(0);setPlaying(v=>!v);}}} onTime={t=>{if(!locked)seek(t);}} onSelect={setSelected} onAddClip={()=>setPanel('animate')} execute={run}/>
    <footer className="statusbar"><span><img src="/mark.svg" alt=""/>Parallax Engine <b>0.1</b></span><div><button disabled={!studio.history.canUndo||locked} onClick={()=>run({op:'undo'})} title="Hoàn tác"><Undo2 size={13}/></button><button disabled={!studio.history.canRedo||locked} onClick={()=>run({op:'redo'})} title="Làm lại"><Redo2 size={13}/></button><span className="mini-divider"/> {studio.connected?'Đã kết nối lõi Rust':'Lõi Rust mất kết nối'} <span className={`status-dot ${studio.connected?'':'offline'}`}/></div><span>{project.assets.length} assets<span className="mini-divider"/>{project.nodes.length} objects<span className="mini-divider"/>rev {project.revision}</span></footer>
    {panel&&<ModalPanel panel={panel} onClose={()=>setPanel(null)} project={project} selected={node} asset={asset} time={clock.current} execute={execute} notify={notify} ffmpeg={studio.ffmpeg} onExport={exporting.start} onSelect={setSelected}/>}
    {toast&&<div className="toast" role="status"><Check size={16}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Đóng thông báo"><X size={14}/></button></div>}
    {studio.error&&project&&<div className="error-banner" role="alert"><span>{studio.error}</span><button onClick={()=>studio.setError('')} aria-label="Đóng lỗi"><X size={14}/></button></div>}
  </div>;
}
